# Read image and cut into 100 px x 100 px patches

In [1]:
import cv2

In [2]:
img = cv2.imread("shadow_remove.jpg")
img

array([[[ 18,  56,  50],
        [  4,  42,  36],
        [  0,  32,  25],
        ...,
        [ 67, 182, 163],
        [ 34, 150, 143],
        [  8, 127, 126]],

       [[ 56, 100,  93],
        [ 42,  87,  78],
        [ 32,  73,  65],
        ...,
        [ 83, 185, 167],
        [ 53, 156, 149],
        [ 26, 128, 127]],

       [[ 49, 109,  98],
        [ 42, 100,  89],
        [ 39,  92,  82],
        ...,
        [106, 186, 169],
        [ 71, 145, 139],
        [ 27,  99,  99]],

       ...,

       [[156, 233, 205],
        [ 86, 171, 139],
        [ 70, 165, 131],
        ...,
        [ 35,  91,  68],
        [ 43, 100,  75],
        [ 51, 108,  83]],

       [[129, 216, 188],
        [ 78, 169, 136],
        [ 72, 167, 130],
        ...,
        [ 46,  97,  77],
        [ 38,  99,  73],
        [ 33, 100,  71]],

       [[ 30, 122,  93],
        [ 48, 142, 108],
        [ 67, 160, 121],
        ...,
        [ 48,  96,  78],
        [ 17,  82,  56],
        [  0,  72,  42]]

In [3]:
img.shape

(20000, 20000, 3)

In [4]:
# Display image
cv2.imshow('image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### One way to get patches, doesn't preserve order

In [20]:
from sklearn.feature_extraction import image

In [14]:
patches = image.extract_patches_2d(img, (100, 100), max_patches= 40000) #img is too large

C:\Anaconda\lib\site-packages\sklearn\feature_extraction\image.py:287: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  indexing_strides = arr[slices].strides


In [21]:
?image.extract_patches_2d

In [15]:
type(patches)

numpy.ndarray

In [16]:
patches.shape

(40000, 100, 100, 3)

In [94]:
img[0:100, 0:100]

array([[[ 18,  56,  50],
        [  4,  42,  36],
        [  0,  32,  25],
        ...,
        [  0,  40,  33],
        [  0,  37,  27],
        [ 16,  72,  61]],

       [[ 56, 100,  93],
        [ 42,  87,  78],
        [ 32,  73,  65],
        ...,
        [  4,  46,  39],
        [  0,  45,  36],
        [ 25,  77,  67]],

       [[ 49, 109,  98],
        [ 42, 100,  89],
        [ 39,  92,  82],
        ...,
        [ 15,  51,  45],
        [ 12,  53,  45],
        [ 34,  80,  67]],

       ...,

       [[ 30,  69,  53],
        [ 27,  63,  47],
        [ 29,  56,  40],
        ...,
        [  6,  62,  51],
        [ 12,  81,  66],
        [ 10,  79,  66]],

       [[ 40,  70,  51],
        [ 33,  61,  42],
        [ 39,  59,  40],
        ...,
        [ 13,  72,  58],
        [ 21,  86,  71],
        [ 18,  80,  68]],

       [[ 47,  76,  60],
        [ 33,  56,  41],
        [ 30,  43,  27],
        ...,
        [ 30,  92,  80],
        [ 38,  98,  87],
        [ 38,  94,  83]]

### Alternatively, get patches by matrix slicing, preserves order

In [93]:
from itertools import product
patches0 = [img[i*100:(i+1)*100,j*100:(j+1)*100] for i, j in product(range(int(img.shape[0]/100)), range(int(img.shape[1]/100)))]

In [94]:
len(patches0)

40000

In [95]:
patches0[0]

array([[[ 18,  56,  50],
        [  4,  42,  36],
        [  0,  32,  25],
        ...,
        [  0,  40,  33],
        [  0,  37,  27],
        [ 16,  72,  61]],

       [[ 56, 100,  93],
        [ 42,  87,  78],
        [ 32,  73,  65],
        ...,
        [  4,  46,  39],
        [  0,  45,  36],
        [ 25,  77,  67]],

       [[ 49, 109,  98],
        [ 42, 100,  89],
        [ 39,  92,  82],
        ...,
        [ 15,  51,  45],
        [ 12,  53,  45],
        [ 34,  80,  67]],

       ...,

       [[ 30,  69,  53],
        [ 27,  63,  47],
        [ 29,  56,  40],
        ...,
        [  6,  62,  51],
        [ 12,  81,  66],
        [ 10,  79,  66]],

       [[ 40,  70,  51],
        [ 33,  61,  42],
        [ 39,  59,  40],
        ...,
        [ 13,  72,  58],
        [ 21,  86,  71],
        [ 18,  80,  68]],

       [[ 47,  76,  60],
        [ 33,  56,  41],
        [ 30,  43,  27],
        ...,
        [ 30,  92,  80],
        [ 38,  98,  87],
        [ 38,  94,  83]]

In [96]:
import numpy as np

In [97]:
patches0 = np.asarray(patches0)

In [98]:
patches0.shape

(40000, 100, 100, 3)

### need to resize patches to feed into pretrained deep network, this is for vgg and resnet models

In [99]:
from copy import deepcopy

patches = deepcopy(patches0)

In [100]:
patches.resize(40000, 224, 224, 3)

In [101]:
patches.shape

(40000, 224, 224, 3)

### on the other hand this is for inception model

In [ ]:
from copy import deepcopy

patches = deepcopy(patches0)

In [ ]:
patches.resize(40000, 299, 299, 3)

#### other, just to test

In [ ]:
# just to test
i=0
for patch in patches:
    cv2.imshow('patch' + str(i), patch)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    i += 1

# Feed patches into pretrained various deep networks

In [37]:
import keras
from keras.applications import vgg19, vgg16, inception_v3, resnet50
from keras.models import Model

#Load the VGG19 model
vgg19_model = vgg19.VGG19(weights='imagenet')#include_top=True, weights='imagenet')#, input_shape=(100, 100, 3))
vgg19_model_fc1 = Model(inputs=vgg19_model.input, outputs=vgg19_model.get_layer('fc1').output)

#Load the VGG16 model
vgg16_model = vgg16.VGG16(weights='imagenet')#include_top=False, weights='imagenet', input_shape=(100, 100, 3))
vgg16_model_fc1 = Model(inputs=vgg16_model.input, outputs=vgg16_model.get_layer('fc1').output)

#Load the Inception_V3 model
inception_model = inception_v3.InceptionV3(weights='imagenet')#include_top=False, weights='imagenet', input_shape=(100, 100, 3))
inception_model_avg_pool = Model(inputs=inception_model.input, outputs=inception_model.get_layer('avg_pool').output)

#Load the ResNet50 model
resnet_model = resnet50.ResNet50(weights='imagenet')#include_top=False, weights='imagenet', input_shape=(100, 100, 3))
resnet_model_avg_pool = Model(inputs=resnet_model.input, outputs=resnet_model.get_layer('avg_pool').output)
resnet_model_fc1000 = Model(inputs=resnet_model.input, outputs=resnet_model.get_layer('fc1000').output)

In [36]:
inception_model.summary()

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_7 (InputLayer)            (None, 299, 299, 3)  0                                            
__________________________________________________________________________________________________
conv2d_95 (Conv2D)              (None, 149, 149, 32) 864         input_7[0][0]                    
__________________________________________________________________________________________________
batch_normalization_95 (BatchNo (None, 149, 149, 32) 96          conv2d_95[0][0]                  
__________________________________________________________________________________________________
activation_144 (Activation)     (None, 149, 149, 32) 0           batch_normalization_95[0][0]     
__________________________________________________________________________________________________
conv2d_96 

In [33]:
resnet_model.summary()

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_8 (InputLayer)            (None, 224, 224, 3)  0                                            
__________________________________________________________________________________________________
conv1_pad (ZeroPadding2D)       (None, 230, 230, 3)  0           input_8[0][0]                    
__________________________________________________________________________________________________
conv1 (Conv2D)                  (None, 112, 112, 64) 9472        conv1_pad[0][0]                  
__________________________________________________________________________________________________
bn_conv1 (BatchNormalization)   (None, 112, 112, 64) 256         conv1[0][0]                      
__________________________________________________________________________________________________
activation

## VGG19

In [48]:
import csv

In [75]:
factor = 100

with open('vgg19_model_fc1_features.csv', 'w') as writeFile:
    writer = csv.writer(writeFile)
    for i in range(int(patches.shape[0]/factor)):
        print(i)
        # prepare the image for the VGG19 model
        processed_image = vgg19.preprocess_input(patches[i*factor:(i+1)*factor,:,:,:])
        vgg19_model_fc1_features = vgg19_model_fc1.predict(processed_image)
        writer.writerows(vgg19_model_fc1_features)
writeFile.close()
        
# # get the predicted probabilities for each class
# predictions = vgg19_model.predict(processed_image)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

In [76]:
import pandas as pd

vgg19_model_fc1_features = pd.read_csv('vgg19_model_fc1_features.csv', sep=',', header=None)

vgg19_model_fc1_features

0         1     2         3         4         5         6         7     \
0       0.0  0.000000   0.0  0.000000  0.000000  1.840619  0.000000  0.000000   
1       0.0  0.000000   0.0  0.817244  0.000000  0.793860  0.000000  0.000000   
2       0.0  0.000000   0.0  1.409605  0.000000  1.455148  0.000000  0.000000   
3       0.0  0.000000   0.0  1.687199  0.000000  3.841550  0.000000  0.828788   
4       0.0  0.000000   0.0  0.011653  0.316097  4.447526  0.000000  0.000000   
5       0.0  0.000000   0.0  0.000000  0.000000  5.225165  0.000000  0.000000   
6       0.0  0.000000   0.0  0.316825  0.000000  8.517784  0.000000  0.351873   
7       0.0  0.000000   0.0  0.000000  0.000000  5.229242  0.000000  0.000000   
8       0.0  0.000000   0.0  1.478508  0.000000  5.276069  0.000000  0.000000   
9       0.0  0.000000   0.0  0.837936  0.000000  5.249379  0.000000  0.000000   
10      0.0  0.000000   0.0  0.000000  0.000000  6.416865  0.000000  0.000000   
11      0.0  0.000000   0.0  0.920354  0.000000  5.510142  0.000000  2.231359   
12      0.0  0.000000   0.0  0.000000  0.000000  4.963728  0.000000  0.000000   
13      0.0  0.000000   0.0  0.130702  0.000000  4.919529  0.000000  0.000000   
14      0.0  0.000000   0.0  0.080646  0.000000  3.392144  0.000000  1.549032   
15      0.0  0.000000   0.0  0.000000  0.000000  5.240513  0.000000  2.366788   
16      0.0  0.000000   0.0  0.184230  0.000000  5.214432  0.000000  0.000000   
17      0.0  0.000000   0.0  0.000000  0.000000  0.726531  0.000000  0.310362   
18      0.0  0.000000   0.0  0.000000  2.446023  0.000000  0.000000  0.000000   
19      0.0  0.000000   0.0  0.000000  0.000000  1.655302  0.000000  0.000000   
20      0.0  0.000000   0.0  0.000000  1.557890  0.000000  0.000000  0.000000   
21      0.0  0.000000   0.0  0.000000  2.173580  0.000000  0.000000  0.000000   
22      0.0  0.000000   0.0  0.000000  0.000000  3.162394  0.000000  1.181414   
23      0.0  0.000000   0.0  0.000000  0.000000  1.033220  0.000000  0.000000   
24      0.0  0.000000   0.0  0.000000  0.000000  2.911303  0.000000  3.721004   
25      0.0  0.000000   0.0  0.000000  0.000000  1.704086  0.000000  0.899822   
26      0.0  0.000000   0.0  0.834250  0.000000  5.976156  0.000000  0.000000   
27      0.0  0.000000   0.0  1.273897  0.000000  1.020377  0.000000  0.000000   
28      0.0  0.000000   0.0  2.573927  0.000000  4.552393  0.000000  1.214468   
29      0.0  0.000000   0.0  1.269917  0.000000  6.798870  0.000000  0.000000   
...     ...       ...   ...       ...       ...       ...       ...       ...   
39970   0.0  4.963865   0.0  3.538324  2.906755  0.000000  1.849956  0.000000   
39971   0.0  4.963865   0.0  3.538324  2.906755  0.000000  1.849956  0.000000   
39972   0.0  4.963865   0.0  3.538324  2.906755  0.000000  1.849956  0.000000   
39973   0.0  4.963865   0.0  3.538324  2.906755  0.000000  1.849956  0.000000   
39974   0.0  4.963865   0.0  3.538324  2.906755  0.000000  1.849956  0.000000   
39975   0.0  4.963865   0.0  3.538324  2.906755  0.000000  1.849956  0.000000   
39976   0.0  4.963865   0.0  3.538324  2.906755  0.000000  1.849956  0.000000   
39977   0.0  4.963865   0.0  3.538324  2.906755  0.000000  1.849956  0.000000   
39978   0.0  4.963865   0.0  3.538324  2.906755  0.000000  1.849956  0.000000   
39979   0.0  4.963865   0.0  3.538324  2.906755  0.000000  1.849956  0.000000   
39980   0.0  4.963865   0.0  3.538324  2.906755  0.000000  1.849956  0.000000   
39981   0.0  4.963865   0.0  3.538324  2.906755  0.000000  1.849956  0.000000   
39982   0.0  4.963865   0.0  3.538324  2.906755  0.000000  1.849956  0.000000   
39983   0.0  4.963865   0.0  3.538324  2.906755  0.000000  1.849956  0.000000   
39984   0.0  4.963865   0.0  3.538324  2.906755  0.000000  1.849956  0.000000   
39985   0.0  4.963865   0.0  3.538324  2.906755  0.000000  1.849956  0.000000   
39986   0.0  4.963865   0.0  3.538324  2.906755  0.000000  1.849956  0.000000   
39987   0.0  4.963865   0.0  3.538324 

In [78]:
vgg19_model_fc1_features.values

array([[0.       , 0.       , 0.       , ..., 0.       , 3.7650242,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 2.2174647,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 4.7347755,
        0.       ],
       ...,
       [0.       , 4.963863 , 0.       , ..., 0.       , 4.436696 ,
        3.064087 ],
       [0.       , 4.963863 , 0.       , ..., 0.       , 4.436696 ,
        3.064087 ],
       [0.       , 4.963863 , 0.       , ..., 0.       , 4.436696 ,
        3.064087 ]])

## VGG16

In [249]:
factor = 100

with open('vgg16_model_fc1_features.csv', 'w') as writeFile:
    writer = csv.writer(writeFile)
    for i in range(int(patches.shape[0]/factor)):
        print(i)
        # prepare the image for the VGG16 model
        processed_image = vgg16.preprocess_input(patches[i*factor:(i+1)*factor,:,:,:])
        vgg16_model_fc1_features = vgg16_model_fc1.predict(processed_image)
        writer.writerows(vgg16_model_fc1_features)
writeFile.close()

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

In [250]:
vgg16_model_fc1_features = pd.read_csv('vgg16_model_fc1_features.csv', sep=',', header=None)

vgg16_model_fc1_features

0         1         2     3         4         5          6     \
0       0.0  0.000000  0.000000   0.0  0.000000  0.000000   0.000000   
1       0.0  0.000000  0.000000   0.0  0.000000  0.000000   5.266844   
2       0.0  0.000000  0.000000   0.0  0.000000  0.000000   5.971231   
3       0.0  0.000000  0.000000   0.0  0.000000  1.929935   3.772087   
4       0.0  0.000000  0.000000   0.0  0.000000  1.556321   5.748743   
5       0.0  0.000000  0.000000   0.0  0.000000  0.000000   5.138688   
6       0.0  0.000000  0.000000   0.0  0.000000  0.000000   7.866478   
7       0.0  0.000000  0.000000   0.0  0.000000  0.000000   6.532898   
8       0.0  0.000000  0.000000   0.0  0.000000  0.986178   6.084032   
9       0.0  0.000000  0.000000   0.0  0.000000  0.730135   6.580358   
10      0.0  0.000000  0.000000   0.0  0.000000  0.480414   6.246459   
11      0.0  0.000000  0.000000   0.0  0.000000  3.232957   6.493121   
12      0.0  0.000000  0.000000   0.0  0.000000  0.201459   4.652407   
13      0.0  0.000000  0.000000   0.0  0.000000  0.000000   3.569503   
14      0.0  0.000000  0.000000   0.0  0.000000  0.000000   5.605175   
15      0.0  0.000000  0.000000   0.0  0.000000  0.000000   6.598345   
16      0.0  0.000000  0.000000   0.0  0.000000  0.000000   4.280669   
17      0.0  0.000000  0.000000   0.0  0.000000  0.000000   2.750694   
18      0.0  0.000000  0.000000   0.0  0.000000  0.000000   1.818586   
19      0.0  0.000000  0.000000   0.0  0.000000  0.000000   3.786489   
20      0.0  0.000000  0.000000   0.0  0.000000  0.000000   2.680190   
21      0.0  0.000000  0.000000   0.0  0.000000  0.000000   0.866598   
22      0.0  0.000000  0.000000   0.0  0.000000  2.457421   2.979418   
23      0.0  0.000000  0.000000   0.0  0.000000  0.000000   4.486362   
24      0.0  0.000000  0.000000   0.0  0.000000  1.062388   2.227049   
25      0.0  0.000000  0.000000   0.0  0.000000  2.898994   3.559895   
26      0.0  0.000000  0.000000   0.0  0.000000  2.722408   4.798355   
27      0.0  0.000000  0.714191   0.0  0.000000  0.000000  10.108670   
28      0.0  0.000000  0.000000   0.0  0.000000  2.892207   3.796594   
29      0.0  0.000000  0.451464   0.0  0.000000  0.000000  10.860747   
...     ...       ...       ...   ...       ...       ...        ...   
39970   0.0  2.603173  0.000000   0.0  0.799981  1.984287   4.026023   
39971   0.0  2.603173  0.000000   0.0  0.799981  1.984287   4.026023   
39972   0.0  2.603173  0.000000   0.0  0.799981  1.984287   4.026023   
39973   0.0  2.603173  0.000000   0.0  0.799981  1.984287   4.026023   
39974   0.0  2.603173  0.000000   0.0  0.799981  1.984287   4.026023   
39975   0.0  2.603173  0.000000   0.0  0.799981  1.984287   4.026023   
39976   0.0  2.603173  0.000000   0.0  0.799981  1.984287   4.026023   
39977   0.0  2.603173  0.000000   0.0  0.799981  1.984287   4.026023   
39978   0.0  2.603173  0.000000   0.0  0.799981  1.984287   4.026023   
39979   0.0  2.603173  0.000000   0.0  0.799981  1.984287   4.026023   
39980   0.0  2.603173  0.000000   0.0  0.799981  1.984287   4.026023   
39981   0.0  2.603173  0.000000   0.0  0.799981  1.984287   4.026023   
39982   0.0  2.603173  0.000000   0.0  0.799981  1.984287   4.026023   
39983   0.0  2.603173  0.000000   0.0  0.799981  1.984287   4.026023   
39984   0.0  2.603173  0.000000   0.0  0.799981  1.984287   4.026023   
39985   0.0  2.603173  0.000000   0.0  0.799981  1.984287   4.026023   
39986   0.0  2.603173  0.000000   0.0  0.799981  1.984287   4.026023   
39987   0.0  2.603173  0.000000   0.0  0.799981  1.984287   4.026023   
39988   0.0  2.603173  0.000000   0.0  0.799981  1.984287   4.026023   
39989   0.0  2.603173  0.000000   0.0  0.799981  1.984287   4.026023   
39990   0.0  2.603173  0.000000   0.0  0.799981  1.984287   4.026023   
39991   0.0  2.603173  0.000000   0.0  0.799981  1.984287   4.026023   
39992   0.0  2.603173  0.000000   0.0  0.799981  1.984287   4.026023   
39993   0.0  2.603173  0.000000   0.0  0.799981

In [251]:
vgg16_model_fc1_features.values

array([[0.        , 0.        , 0.        , ..., 0.        , 0.3375473 ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 2.6031728 , 0.        , ..., 1.7739973 , 0.98970115,
        3.9133618 ],
       [0.        , 2.6031728 , 0.        , ..., 1.7739973 , 0.98970115,
        3.9133618 ],
       [0.        , 2.6031728 , 0.        , ..., 1.7739973 , 0.98970115,
        3.9133618 ]])

## Inception_V3***
need to make sure patches is of shape (40000, 299, 299, 3)

In [254]:
factor = 100

with open('inception_model_avg_pool_features.csv', 'w') as writeFile:
    writer = csv.writer(writeFile)
    for i in range(int(patches.shape[0]/factor)):
        print(i)
        # prepare the image for the Inception model
        processed_image = inception_v3.preprocess_input(patches[i*factor:(i+1)*factor,:,:,:])
        inception_model_avg_pool_features = inception_model_avg_pool.predict(processed_image)
        writer.writerows(inception_model_avg_pool_features)
writeFile.close()

0


ValueError: Error when checking input: expected input_11 to have shape (299, 299, 3) but got array with shape (224, 224, 3)

In [ ]:
inception_model_avg_pool_features = pd.read_csv('inception_model_avg_pool_features.csv', sep=',', header=None)

inception_model_avg_pool_features

In [ ]:
inception_model_avg_pool_features.values

## ResNet

In [255]:
factor = 100

with open('resnet_model_avg_pool_features.csv', 'w') as writeFile:
    writer = csv.writer(writeFile)
    for i in range(int(patches.shape[0]/factor)):
        print(i)
        # prepare the image for the Inception model
        processed_image = resnet50.preprocess_input(patches[i*factor:(i+1)*factor,:,:,:])
        resnet_model_avg_pool_features = resnet_model_avg_pool.predict(processed_image)
        writer.writerows(resnet_model_avg_pool_features)
writeFile.close()

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

In [256]:
resnet_model_avg_pool_features = pd.read_csv('resnet_model_avg_pool_features.csv', sep=',', header=None)

resnet_model_avg_pool_features

0         1         2         3         4     5         6     \
0      0.321032  0.000000  0.170868  0.142426  0.156579   0.0  0.000000   
1      0.025914  0.077498  0.030362  0.190770  0.409243   0.0  0.011032   
2      0.101121  0.000000  0.000000  0.001034  0.038722   0.0  0.000000   
3      0.251231  0.000000  0.000000  0.182683  0.056033   0.0  0.000000   
4      0.000000  0.000000  0.023521  0.136637  0.001189   0.0  0.000000   
5      0.360913  0.000000  0.059153  0.000000  0.001419   0.0  0.000000   
6      0.100614  0.000000  0.000000  0.000000  0.000000   0.0  0.004615   
7      0.265906  0.000000  0.000000  0.000315  0.058065   0.0  0.000000   
8      0.437832  0.000000  0.000000  0.027636  0.003797   0.0  0.000000   
9      0.186707  0.000000  0.000000  0.013718  0.002266   0.0  0.000000   
10     0.206755  0.000000  0.000000  0.000000  0.222391   0.0  0.000000   
11     0.332473  0.000000  0.000000  0.009968  0.076063   0.0  0.002844   
12     0.145819  0.000000  0.051334  0.097454  0.000000   0.0  0.000000   
13     0.121339  0.000000  0.000000  0.051551  0.279236   0.0  0.000000   
14     0.072548  0.000000  0.000000  0.028101  0.045212   0.0  0.000000   
15     0.137588  0.000000  0.000000  0.009120  0.018999   0.0  0.000000   
16     0.118538  0.000000  0.122533  0.000000  0.078096   0.0  0.007462   
17     0.589884  0.000000  0.008124  0.155532  0.000000   0.0  0.000000   
18     0.000000  0.035877  0.536791  0.527866  0.000000   0.0  0.000000   
19     0.000000  0.010232  0.000000  0.000000  0.152903   0.0  0.000000   
20     0.362607  0.004025  0.384927  0.036915  0.000000   0.0  0.000000   
21     0.015781  0.017766  0.196692  0.001394  0.033779   0.0  0.000000   
22     0.035434  0.005369  0.010195  0.084761  0.000000   0.0  0.002210   
23     0.025219  0.000000  0.009287  0.000000  0.083453   0.0  0.000000   
24     0.094730  0.000331  0.000000  0.017501  0.000000   0.0  0.000000   
25     0.246937  0.000000  0.000000  0.006549  0.053683   0.0  0.000000   
26     0.202587  0.000000  0.000000  0.000000  0.004364   0.0  0.000000   
27     0.062092  0.000000  0.000000  0.000000  0.964990   0.0  0.006885   
28     0.010814  0.000000  0.000000  0.008541  0.464768   0.0  0.174819   
29     0.000000  0.000000  0.000000  0.000000  0.244088   0.0  0.047098   
...         ...       ...       ...       ...       ...   ...       ...   
39970  0.000000  0.000000  0.000000  0.000000  0.000000   0.0  0.000000   
39971  0.000000  0.000000  0.000000  0.000000  0.000000   0.0  0.000000   
39972  0.000000  0.000000  0.000000  0.000000  0.000000   0.0  0.000000   
39973  0.000000  0.000000  0.000000  0.000000  0.000000   0.0  0.000000   
39974  0.000000  0.000000  0.000000  0.000000  0.000000   0.0  0.000000   
39975  0.000000  0.000000  0.000000  0.000000  0.000000   0.0  0.000000   
39976  0.000000  0.000000  0.000000  0.000000  0.000000   0.0  0.000000   
39977  0.000000  0.000000  0.000000  0.000000  0.000000   0.0  0.000000   
39978  0.000000  0.000000  0.000000  0.000000  0.000000   0.0  0.000000   
39979  0.000000  0.000000  0.000000  0.000000  0.000000   0.0  0.000000   
39980  0.000000  0.000000  0.000000  0.000000  0.000000   0.0  0.000000   
39981  0.000000  0.000000  0.000000  0.000000  0.000000   0.0  0.000000   
39982  0.000000  0.000000  0.000000  0.000000  0.000000   0.0  0.000000   
39983  0.000000  0.000000  0.000000  0.000000  0.000000   0.0  0.000000   
39984  0.000000  0.000000  0.000000  0.000000  0.000000   0.0  0.000000   
39985  0.000000  0.000000  0.000000  0.000000  0.000000   0.0  0.000000   
39986  0.000000  0.000000  0.000000  0.000000  0.000000   0.0  0.000000   
39987  0.000000  0.000000  0.000000  0.000000  0.000000   0.0  0.000000   
39988  0.000000  0.000000  0.000000  0.000000  0.000000   0.0  0.000000   
39989  0.000000  0.000000  0.000000  0.000000  0.000000   0.0  0.000000   
39990  0.000000  0.000000  0.000000  0.000000  0.000000   0.0  0.000000   
39991  0.000000  0.000000  0.000000 

In [257]:
resnet_model_avg_pool_features.values

array([[0.3210324 , 0.        , 0.17086771, ..., 0.        , 0.        ,
        0.        ],
       [0.02591365, 0.07749757, 0.03036218, ..., 0.018252  , 0.        ,
        0.        ],
       [0.10112111, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

# Clustering

In [79]:
%matplotlib inline
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

## KMeans VGG19

In [80]:
kmeans = KMeans(n_clusters=20)

In [81]:
kmeans.fit(vgg19_model_fc1_features.values)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=20, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [82]:
output = kmeans.predict(vgg19_model_fc1_features.values)

In [84]:
output

array([ 1, 15,  5, ...,  0,  0,  0])

In [109]:
output.shape

(40000,)

In [119]:
str(output[0])

'1'

In [270]:
# Visualization
labels = ["cluster" + str(i) for i in range(20)]
cluster_dict = dict.fromkeys(labels, None) # dict with cluster number as keys and indices of relevant patches as values

for i in range(len(output)):
    if cluster_dict["cluster" + str(output[i])] == None:
        cluster_dict["cluster" + str(output[i])] = [i]
    else:
        cluster_dict["cluster" + str(output[i])].append(i)

maxcount = max(len(v) for v in cluster_dict.values())
max_clusters = [k for k, v in cluster_dict.items() if len(v) == maxcount]


In [271]:
max_clusters

['cluster0']

In [272]:
type(patches0)

numpy.ndarray

In [273]:
type(img)

numpy.ndarray

In [274]:
import random

for cluster in max_clusters:
    # we will view a random 25 patches for each cluster
    indices = cluster_dict[cluster] # indices of patches
    indices_pos = random.sample(range(len(indices)), 25) # positions of selected elements in indices
    
    # create new_img and initialize with the first patch 
    new_img = np.array(patches0[indices[indices_pos[0]]])
    
    # also create row_img, which will hold our image so far for a particular row_img, a temporary convenient variable
    row_img = np.array(patches0[indices[indices_pos[0]]])
    
    for i in range(len(indices_pos)):
        if i == 0: # we already did it outside of the loop
            continue
        if i%5:
            # stack vertically and start new row_img
            np.concatenate((new_img, row_img), axis=0)
            row_img = np.array(patches0[indices[indices_pos[i]]])
        else:
            np.concatenate((row_img, patches0[indices[indices_pos[i]]]), axis=1)
        
    cv2.imwrite('vgg19_model_fc1_' + cluster +'.jpg', new_img)
        

In [ ]:
## need to add white line dividers between patches

In [275]:
# Read image
cluster_img = cv2.imread('vgg19_model_fc1_cluster0.jpg')
# Display image
cv2.imshow('vgg19_model_fc1_cluster0', cluster_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# KMeans VGG16

In [33]:
kmeans = KMeans(n_clusters=3)

## KMeans Inception_V3***

## KMeans ResNet